### ISSUE TITLE
使用哪一个基座模型？

### ISSUE THREAD

**Issue by LinB203** [OpenBMB/OmniLMM#10]
我观察到minicpm的llm有多个版本，例如fp32，bf16，dpo和sft。
请问多模态模型是使用哪一个llm呢？

**Comment by yaoyuanTHU** [comment]
你好，直接下载v-bf16就可以使用，不需要单独下载语言模型哈

**Comment by LinB203** [comment]
hi，我想你误会了，我是想要用在自己的工作上，因此我好奇你的多模态的llm是基于哪个llm训的。

> 你好，直接下载v-bf16就可以使用，不需要单独下载语言模型哈

**Comment by iceflame89** [comment]
LLM used in OmniLMM-3B ： https://huggingface.co/openbmb/MiniCPM-2B-sft-bf16
