### ISSUE TITLE
数学推理出现幻觉？

### ISSUE THREAD

**Issue by soBigBang** [OpenBMB/OmniLMM#12]
数学推理出错
prompt:  1+1/sqrt(2)=?
completion:   1 + 1/sqrt(2) 可以转换为一个数学表达式。

首先，我们可以将根号下的 2 化简为 √2。

然后，我们可以将 1 视为一个常数，并将其加到 1/√2。为了将 1/√2 转换为一个分数，我们可以将其看作是一个带根号的分数。我们可以将根号下的 2 平方，得到 2。因此，1/√2 可以表示为 1/(√2 * √2)，即 1/(2 * 2)。

现在，我们可以将 1 + 1/√2 表示为：

1 + 1/√2 = 1 + 1/2

接下来，我们可以将这个表达式转换为一个带分数：

1 + 1/√2 = 2/2 + 1/2 = 3/2

所以，1 + 1/√2 的结果是 3/2 或 1 1/2。

**Comment by yaoyuanTHU** [comment]
你好，感谢反馈！如果是多模态样例的话，请同时发送一下图片，我们会持续改进。如果是纯文本样例的话，使用[MiniCPM](https://github.com/OpenBMB/MiniCPM/tree/main?tab=readme-ov-file#4)进行推理效果会更好哈.
