### ISSUE TITLE
P40上执行示例代码出错ImportError: /home/ubuntu/.local/lib/python3.10/site-packages/flash_attn_2_cuda.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c104cuda9SetDeviceEi

### ISSUE THREAD

**Issue by akan** [OpenBMB/OmniLMM#13]
重装flash_attn_2也不能解决。
还是同样错误

**Comment by iceflame89** [comment]
We have updated the code in huggingface model `openbmb/MiniCPM-V`, which would not force to install flash_attn.
Please  uninstall flash_attn and try again.
