### ISSUE TITLE
Error about missing methods

### ISSUE THREAD

**Issue by Marlod390** [OpenBMB/OmniLMM#14]
Hello. I'm getting followed error when i try to run the demo of MiniCPM-V on Ubuntu 22.04：
`(OmniLMM) markusc@ubuntu2:~/github/OmniLMM$ /home/markusc/anaconda3/envs/OmniLMM/bin/python /home/markusc/github/OmniLMM/infer.py
Loading checkpoint shards: 100%|████████████████████████████████████████████| 2/2 [00:01<00:00,  1.94it/s]
Traceback (most recent call last):
  File "/home/markusc/github/OmniLMM/infer.py", line 10, in <module>
    answer = chat_model.process(inputs)
AttributeError: 'OmniLMMChat' object has no attribute 'process'`

Apart from importing the json module and changing the model path to openbmb/MiniCPM-V, I did not make any modifications to the original code. As followed: 

`from chat import OmniLMMChat, img2base64
import json
chat_model = OmniLMMChat('openbmb/MiniCPM-V') 

im_64 = img2base64('./assets/worldmap_ck.jpg')

msgs = [{"role": "user", "content": "What is interesting about this image?"}]

inputs = {"image": im_64, "question": json.dumps(msgs)}
answer = chat_model.process(inputs)
print(answer)

msgs.append({"role": "assistant", "content": answer})
msgs.append({"role": "user", "content": "Where is China in the image"})

inputs = {"image": im_64, "question": json.dumps(msgs)}
answer = chat_model.process(inputs)
print(answer)`

Thanks in advance.

**Comment by Marlod390** [comment]
I manually changed `answer = chat_model.process(inputs)`  to `answer = chat_model.chat(inputs)` and it works fine now.

**Comment by iceflame89** [comment]
Thanks for the report,  fixed now
