### ISSUE TITLE
可否提供一下预训练部分数据的来源？

### ISSUE THREAD

**Issue by lucasjinreal** [OpenBMB/OmniLMM#17]
Or, just opensource the training data

**Comment by YuzaChongyi** [comment]
OmniLMM-12B 预训练数据主要来自 laion-2b、laion-coco、coco、visual genome、cc3m、cc12m，OmniLMM-3B 是双语多模态模型，还额外加入了 wukong、zero-chinese、laion-2b-chinese 这些中文图文 pair 数据集

**Comment by lucasjinreal** [comment]
wukong laion-2b 中文部分噪音挺大的，就直接用了？
另外感觉ocr能力较差，为啥不加入更多的ocr数据？

**Comment by YuzaChongyi** [comment]
> wukong laion-2b 中文部分噪音挺大的，就直接用了？ 另外感觉ocr能力较差，为啥不加入更多的ocr数据？

需要做一些数据清洗过滤一些低质数据，ocr 能力的话我们后续会更新

**Comment by lucasjinreal** [comment]
@YuzaChongyi  可否连同数据预处理的方式一同开源呢？ 否则意义不是特别大，也没法复现

**Comment by YuzaChongyi** [comment]
> @YuzaChongyi 可否连同数据预处理的方式一同开源呢？ 否则意义不是特别大，也没法复现

抱歉，关于数据预处理的代码我们可能不会开源，因为有一些策略是模型策略，涉及到一些内部的模型，我们后续会在技术报告中介绍这一部分
