### ISSUE TITLE
MMMU val 分数疑问

### ISSUE THREAD

**Issue by Isaachhh** [OpenBMB/OmniLMM#19]
关于MiniCPM-V，我注意到Github上报告MMMU val 34.7，而[官方leaderboard](https://mmmu-benchmark.github.io/)是37.2？

**Comment by yiranyyu** [comment]
目前在官方的 [githubio 网站](https://mmmu-benchmark.github.io)榜单上仅有 OmniLMM-12B 41.1(val) 的结果。

**Comment by Isaachhh** [comment]
![20240214-155356](https://github.com/OpenBMB/OmniLMM/assets/93458689/be98cd4b-3ff2-4a8b-b103-f1286d356c97)
@yiranyyu 榜单上有MiniCPM-V (OmniLMM-3B) 37.2 (val)的结果

**Comment by yiranyyu** [comment]
抱歉，先前回复中遗漏了相关信息。此处 OmniLMM-3B (MiniCPM-V) 模型在 github readme 内分数偏低的原因是我们的评测提示词和提交到官网结果所用**提示词不同**。使用 [VLMEval Kit](https://github.com/open-compass/VLMEvalKit) 的**默认提示词即可复现** 37.2 结果。

**Comment by Isaachhh** [comment]
明白了，感谢！
