### ISSUE TITLE
请问支持中文提问和回答吗?

### ISSUE THREAD

**Issue by fishfree** [OpenBMB/OmniLMM#20]
我看示例截图里都是英语的.

**Comment by yiranyyu** [comment]
OmniLMM-3B 模型原生支持中文问答，OmniLMM-12B 可以理解简单中文指令但是**一般会做出英文回答**。利用我们在这篇[论文](https://arxiv.org/pdf/2308.12038.pdf)中提出的技术，你可以通过少量中文多模态指令数据微调赋予模型中文问答能力。
