### ISSUE TITLE
和yi-vl-34b相比如何？

### ISSUE THREAD

**Issue by xxm1668** [OpenBMB/OmniLMM#23]

**Comment by iceflame89** [comment]
Look https://rank.opencompass.org.cn/leaderboard-multimodal for more benchmark results.
<img width="1210" alt="Screenshot 2024-03-01 at 10 34 25" src="https://github.com/OpenBMB/OmniLMM/assets/5380770/02d24625-5e87-4e5c-9845-aa172c174e5c">
<img width="1205" alt="Screenshot 2024-03-01 at 10 34 46" src="https://github.com/OpenBMB/OmniLMM/assets/5380770/ba15afb5-4f39-4665-8b05-29701f867516">

**Comment by xxm1668** [comment]
_谢谢
