### ISSUE TITLE
MiniCPM-v和OmniLMM是啥关系？应该用哪个？

### ISSUE THREAD

**Issue by xylcbd** [OpenBMB/OmniLMM#30]

**Comment by xylcbd** [comment]
这个3B的模型加载报错：Unknown model (vit_so400m_patch14_siglip_384)

**Comment by iceflame89** [comment]
OmniLMM包含12B和3B两个模型，其中OmniLMM-3B是基于MiniCPM作为LLM部分，所以又称为MiniCPM-V。
请根据参数规模按需选择
