### ISSUE TITLE
object hal的评估方法

### ISSUE THREAD

**Issue by Mr-Loevan** [OpenBMB/OmniLMM#35]
请问榜单里给出的object hal的分数是如何计算的，和RLHF-V中的计算方式是否有不同。
![image](https://github.com/OpenBMB/OmniLMM/assets/70183000/99ed2db9-2d6c-4cdb-a98d-bec02c66b668)

**Comment by yiranyyu** [comment]
你好，计算方式并无不同，在 RLHF-V 论文中我们汇报的是越低越好的【幻觉率】，在本代码仓库 README 中汇报的是和【幻觉率】互补的【精确度】（两者之和为 100）。
